# state_manager.py

""" This file handels maintaining of the model and  keep necessary volatile information about model aggregation """

 

# importing necessary libraries

import logging
import numpy as np
import time
from typing import Dict, Any
from fl_main.lib.util.data_struc import LimitedDict
from fl_main.lib.util.helpers import generate_id, generate_model_id
from fl_main.lib.util.states import IDPrefix


#create class
class StateManager : 
    """keeps the track of the state of the aggregator 
        The volatile info of the aggregator and agent like local models, agent's info connected to the aggregator , cluster models generated by aggregation process,  current round number"""
    
    def __init__(self):
        self.id = generate_id() #unique id to aggregator
        self.agent_set  = list() #set of agents conn. to aggregator
        self.mnames = list() #name of each layer of ml model 
        self.round = 0 # aggregation round
        self.local_model_buffers = LimitedDict(self.mnames) #list of local models 
        self.local_model_num_samples = list() # stores no. of datasamples  coluplected in buffer
        self.cluster_models = LimitedDict(self.mnames) #collection of globa cluster models by names
        self.cluster_model_ids = list() #list of ids of cluster models created by this aggregator
        self.initialized = False 
        self.agg_threshold = 1.0

        

    def initialze_model_info(self, lmodels, init_weights_flag):
        """setup the initial global model to be used by agents"""
        """
        Initialize the structure of NNs (numpy.array) based on the first models received
        :param models: lmodels - local ML models
        :param models: init_weights_flag - for initializing base model
        :return:
        """

        for key in lmodels.key():
            self.mnames.append(key)

        self.local_model_buffers = LimitedDict(self.mnames)
        self.cluster_models = LimitedDict(self.mnames)

        # Clear all models saved and buffered
        self.clear_lmodel_buffers()

        if init_weights_flag : 
            # Use the received local models as the cluster model (init base models)
            self.initialize_models(lmodels, weight_keep =  init_weights_flag)
        else : 
            # initialize the model with zeros
            self.initialize_models(lmodels, weight_keep = False)


    def initialize_models(self ,  model : Dict [str , np.array], weight_keep : bool = False):
        """Initialize structure of neural networks based on the first model receive"""

        """
        Clears old models.Loops through each expected model name.
        Either:
            Keeps the provided weights (if weight_keep=True), or
            Replaces them with zero-initialized weights (same shape).
        Stores them in self.cluster_models with a unique ID in self.cluster_model_ids.
        Marks the system as initialized and logs the event."""

        self.clear_saved_models()

        for mname in self.mnames:
            if weight_keep: 
                m = model[mname]
            else : 
                # keep the weights given as init weights
                m = np.zeros_like(model[mname])

            #create cluster model and its id
            self.cluster_models[mname].append(m)
            id = generate_model_id( IDPrefix.aggregator, self.id, time.time())
            self.cluster_model_ids.append(id)

        self.initialized = True # set that it will never be call automatically
        logging.info(f'--- Model Formats initialized, model names: {self.mnames} ---')
    

################ Initializing the model is done ##############
################ Now, checking aggregation criteria ##########

    def ready_for_local_aggregation(self):
        if len(self.mnames) == 0:
            return False
        num_agents = int(self.agg_threshold * len(self.agent_set))

        if num_agents == 0: num_agents = 1
        num_collected_lmodels = len(self.local_model_buffers[self.mnames[0]])
        if num_collected_lmodels >= num_agents:
            return True
        else:
            return False
        

        
############## Now, buffering the local modle that are used for aggregation process ############

    def buffer_local_models(self, models :  Dict[str, np.array], participate = False , meta_data : Dict[Any, Any] = {} ): 
        #store local models from agent into the local buffer model

        if not participate :  # if it is an actual models (not in participation message)
            for key, model in models.items():
                self.local_model_buffers[key].append(model) 

            try : 
                num_samples = meta_data["num_sample"]

            except : 
                num_samples = 1

            self.local_model_num_samples.append(int(num_samples))

        else : 
            pass
        
        # if the cluster models have not been initialized
        # first time call only
        if not self.initialized : 
            self.initialize_models(models)

    def clear_saved_models(self):
        """
        Clear all models stored for a next round (cluster models)
        :return:
        """
        for mname in self.mnames:
            self.cluster_models[mname].clear()

    def clear_lmodel_buffers(self):
        """
        Clear all buffered local models for a next round
        :return:
        """
        for mname in self.mnames:
            self.local_model_buffers[mname].clear()
        self.local_model_num_samples = list()

    def add_agent(self, agent_name: str, agent_id: str, agent_ip: str, socket: str):
        """
        Save the info of an agent
        :param agent_name: str - agent name
        :param agent_id: str - agent ID
        :param agent_ip: str - agent IP address
        :param socket: str - port number to the agent
        :return: agent_id, socket
        """
        for agent in self.agent_set:
            if agent_name == agent['agent_name']:
                print(f'{agent_name} already exists.')
                return  agent['agent_id'], agent['socket']

        agent = {
            'agent_name': agent_name,
            'agent_id': agent_id,
            'agent_ip': agent_ip,
            'socket': socket
        }
        self.agent_set.append(agent)
        return agent_id, socket

    def increment_round(self):
        """
        Increment the round number (called after each global model synthesis)
        :return:
        """
        self.round += 1 